In [280]:
import sqlite3
import pandas as pd

In [281]:
conn = sqlite3.connect('dummy.sqlite3')


In [282]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)


         name
0  regression


In [283]:
table_list = pd.read_sql_query("SELECT * FROM regression;", conn)
print(table_list)



            TestId ProjectName                CycleName TestPriority  \
0      SDPTST-1658        CBAC        Sprint4_AM_Europa       Medium   
1      SDPTST-3073        CBAC        Sprint4_AM_Europa          Low   
2      SDPTST-1360        CBAC        Sprint4_AM_Europa         High   
3      SDPTST-3071        CBAC        Sprint4_AM_Europa          Low   
4      SDPTST-8369        CBAC        Sprint4_AM_Europa         High   
...            ...         ...                      ...          ...   
81509  BBA02-18987        CBAC  PI2023.1-Sprint5-Manual    Very High   
81510  BBA02-18989        CBAC  PI2023.1-Sprint5-Manual    Very High   
81511  BBA02-18996        CBAC  PI2023.1-Sprint5-Manual    Very High   
81512  BBA02-18986        CBAC  PI2023.1-Sprint5-Manual    Very High   
81513  BBA02-19000        CBAC  PI2023.1-Sprint5-Manual    Very High   

           Defect1      Defect2      Defect3      Defect4 DefectStatus1  \
0      BBA02-14075   BBA02-7530  SDPON-29022  SDPON-28992   

In [284]:
table_list.head()

TestId ProjectName          CycleName TestPriority      Defect1  \
0  SDPTST-1658        CBAC  Sprint4_AM_Europa       Medium  BBA02-14075   
1  SDPTST-3073        CBAC  Sprint4_AM_Europa          Low  BBA02-42408   
2  SDPTST-1360        CBAC  Sprint4_AM_Europa         High  BBA02-11401   
3  SDPTST-3071        CBAC  Sprint4_AM_Europa          Low  BBA02-36096   
4  SDPTST-8369        CBAC  Sprint4_AM_Europa         High    JMAP-5294   

       Defect2      Defect3      Defect4 DefectStatus1 DefectStatus2  \
0   BBA02-7530  SDPON-29022  SDPON-28992        Closed        Closed   
1  BBA02-36096  BBA02-29859  BBA02-24086        Closed        Closed   
2   BBA02-8089   BBA02-1335  SDPON-32283        Closed        Closed   
3  BBA02-30987  BBA02-29859  BBA02-25599        Closed        Closed   
4    JMAP-5197    JMAP-5295  BBA02-40188        Closed           WIP   

  DefectStatus3 DefectStatus4   Result    TestCaseId  
0        Closed        Closed     PASS  SDPTST-10269  
1      Assigned        Closed  Blocked  SDPTST-10269  
2        Closed        Closed     PASS  SDPTST-10269  
3      Assigned        Closed     FAIL  SDPTST-10269  
4        Closed        Closed     FAIL  SDPTST-10269

In [285]:
table_list.isnull().sum()

TestId           0
ProjectName      0
CycleName        0
TestPriority     0
Defect1          0
Defect2          0
Defect3          0
Defect4          0
DefectStatus1    0
DefectStatus2    0
DefectStatus3    0
DefectStatus4    0
Result           0
TestCaseId       0
dtype: int64

In [286]:
table_list = table_list.drop(['TestCaseId'], axis=1)


In [287]:
table_list=table_list.drop(['TestId'],axis=1)

In [288]:
table_list=table_list.drop(['ProjectName'],axis=1)

In [289]:
table_list.head()

CycleName TestPriority      Defect1      Defect2      Defect3  \
0  Sprint4_AM_Europa       Medium  BBA02-14075   BBA02-7530  SDPON-29022   
1  Sprint4_AM_Europa          Low  BBA02-42408  BBA02-36096  BBA02-29859   
2  Sprint4_AM_Europa         High  BBA02-11401   BBA02-8089   BBA02-1335   
3  Sprint4_AM_Europa          Low  BBA02-36096  BBA02-30987  BBA02-29859   
4  Sprint4_AM_Europa         High    JMAP-5294    JMAP-5197    JMAP-5295   

       Defect4 DefectStatus1 DefectStatus2 DefectStatus3 DefectStatus4  \
0  SDPON-28992        Closed        Closed        Closed        Closed   
1  BBA02-24086        Closed        Closed      Assigned        Closed   
2  SDPON-32283        Closed        Closed        Closed        Closed   
3  BBA02-25599        Closed        Closed      Assigned        Closed   
4  BBA02-40188        Closed           WIP        Closed        Closed   

    Result  
0     PASS  
1  Blocked  
2     PASS  
3     FAIL  
4     FAIL

In [290]:
X = table_list.drop('Result', axis=1)  # All features
y = table_list['Result']              # Target


In [291]:
table_list.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81514 entries, 0 to 81513
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   CycleName      81514 non-null  object
 1   TestPriority   81514 non-null  object
 2   Defect1        81514 non-null  object
 3   Defect2        81514 non-null  object
 4   Defect3        81514 non-null  object
 5   Defect4        81514 non-null  object
 6   DefectStatus1  81514 non-null  object
 7   DefectStatus2  81514 non-null  object
 8   DefectStatus3  81514 non-null  object
 9   DefectStatus4  81514 non-null  object
 10  Result         81514 non-null  object
dtypes: object(11)
memory usage: 6.8+ MB


In [292]:
print(len(X))
print(len(y))


81514
81514


In [293]:
table_list.tail()

CycleName TestPriority      Defect1    Defect2  \
81509  PI2023.1-Sprint5-Manual    Very High  BBA02-21159  JMAP-4229   
81510  PI2023.1-Sprint5-Manual    Very High  BBA02-19868       None   
81511  PI2023.1-Sprint5-Manual    Very High         None       None   
81512  PI2023.1-Sprint5-Manual    Very High    JMAP-4273       None   
81513  PI2023.1-Sprint5-Manual    Very High         None       None   

           Defect3 Defect4 DefectStatus1 DefectStatus2 DefectStatus3  \
81509  BBA02-21660    None        Closed        Closed        Closed   
81510         None    None        Closed          None          None   
81511         None    None          None          None          None   
81512         None    None        Closed          None          None   
81513         None    None          None          None          None   

      DefectStatus4 Result  
81509          None   PASS  
81510          None   PASS  
81511          None   PASS  
81512          None   PASS  
81513          None   PASS

In [294]:
X = X.loc[y.index]
y.shape



(81514,)

In [295]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=True, handle_unknown='ignore')

In [296]:
# Fit and transform, but DO NOT convert to dense array
X_encoded_sparse = encoder.fit_transform(table_list[[
    'CycleName', 'TestPriority', 'Defect1', 'Defect2', 'Defect3', 'Defect4',
    'DefectStatus1', 'DefectStatus2', 'DefectStatus3', 'DefectStatus4',
]])

In [297]:
print(X_encoded_sparse)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 815140 stored elements and shape (81514, 6827)>
  Coords	Values
  (0, 118)	1.0
  (0, 164)	1.0
  (0, 250)	1.0
  (0, 3803)	1.0
  (0, 5867)	1.0
  (0, 6758)	1.0
  (0, 6794)	1.0
  (0, 6804)	1.0
  (0, 6813)	1.0
  (0, 6821)	1.0
  (1, 118)	1.0
  (1, 162)	1.0
  (1, 1046)	1.0
  (1, 3354)	1.0
  (1, 4931)	1.0
  (1, 6039)	1.0
  (1, 6794)	1.0
  (1, 6804)	1.0
  (1, 6811)	1.0
  (1, 6821)	1.0
  (2, 118)	1.0
  (2, 161)	1.0
  (2, 188)	1.0
  (2, 3809)	1.0
  (2, 4686)	1.0
  :	:
  (81511, 6617)	1.0
  (81511, 6797)	1.0
  (81511, 6806)	1.0
  (81511, 6815)	1.0
  (81511, 6823)	1.0
  (81512, 39)	1.0
  (81512, 159)	1.0
  (81512, 2044)	1.0
  (81512, 4416)	1.0
  (81512, 5712)	1.0
  (81512, 6617)	1.0
  (81512, 6794)	1.0
  (81512, 6806)	1.0
  (81512, 6815)	1.0
  (81512, 6823)	1.0
  (81513, 39)	1.0
  (81513, 159)	1.0
  (81513, 2544)	1.0
  (81513, 4416)	1.0
  (81513, 5712)	1.0
  (81513, 6617)	1.0
  (81513, 6797)	1.0
  (81513, 6806)	1.0
  (81513, 6815)	1.0
  

In [298]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [299]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded_sparse, y_encoded,test_size=0.20,random_state=42)

In [300]:
##Model training

from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')


In [301]:
logistic.fit(X_train, y_train)
y_pred=logistic.predict(X_test)


c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [302]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.876832484818745
[[   33    33     5     6   195]
 [    9   308    19    17   907]
 [    2    40    53    25   227]
 [    1    26     2  1600   174]
 [   17   219    66    18 12301]]
              precision    recall  f1-score   support

           0       0.53      0.12      0.20       272
           1       0.49      0.24      0.33      1260
           2       0.37      0.15      0.22       347
           3       0.96      0.89      0.92      1803
           4       0.89      0.97      0.93     12621

    accuracy                           0.88     16303
   macro avg       0.65      0.48      0.52     16303
weighted avg       0.85      0.88      0.86     16303



HYPERPARAMETER TUNING

In [303]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [304]:
params={'penalty':penalty,'C':c_values,'solver':solver}

In [305]:
from sklearn.model_selection import RandomizedSearchCV

In [306]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy',n_iter=10,n_jobs=-1,random_state=42)

In [307]:
randomcv.fit(X_train,y_train)

c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logist

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   random_state=42, scoring='accuracy')

In [308]:
randomcv.best_score_

np.float64(0.8808789837603559)

In [309]:
randomcv.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [310]:
model=LogisticRegression(solver='lbfgs',penalty='l2',C=0.1)

In [311]:
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

In [312]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8767098080107956
              precision    recall  f1-score   support

           0       0.64      0.05      0.10       272
           1       0.51      0.19      0.28      1260
           2       0.39      0.10      0.16       347
           3       0.98      0.88      0.93      1803
           4       0.88      0.98      0.93     12621

    accuracy                           0.88     16303
   macro avg       0.68      0.44      0.48     16303
weighted avg       0.85      0.88      0.85     16303

[[   14    30     3     0   225]
 [    3   241     7     4  1005]
 [    1    23    34    20   269]
 [    0    19     0  1593   191]
 [    4   160    44     2 12411]]
