In [1]:
import sqlite3
import pandas as pd
import numpy as np

In [2]:
conn = sqlite3.connect('dummy.sqlite3')


In [3]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)


         name
0  regression


In [4]:
table_list = pd.read_sql_query("SELECT * FROM regression;", conn)
print(table_list)



            TestId ProjectName                CycleName TestPriority  \
0      SDPTST-1658        CBAC        Sprint4_AM_Europa       Medium   
1      SDPTST-3073        CBAC        Sprint4_AM_Europa          Low   
2      SDPTST-1360        CBAC        Sprint4_AM_Europa         High   
3      SDPTST-3071        CBAC        Sprint4_AM_Europa          Low   
4      SDPTST-8369        CBAC        Sprint4_AM_Europa         High   
...            ...         ...                      ...          ...   
81509  BBA02-18987        CBAC  PI2023.1-Sprint5-Manual    Very High   
81510  BBA02-18989        CBAC  PI2023.1-Sprint5-Manual    Very High   
81511  BBA02-18996        CBAC  PI2023.1-Sprint5-Manual    Very High   
81512  BBA02-18986        CBAC  PI2023.1-Sprint5-Manual    Very High   
81513  BBA02-19000        CBAC  PI2023.1-Sprint5-Manual    Very High   

           Defect1      Defect2      Defect3      Defect4 DefectStatus1  \
0      BBA02-14075   BBA02-7530  SDPON-29022  SDPON-28992   

In [5]:
table_list.head()

TestId ProjectName          CycleName TestPriority      Defect1  \
0  SDPTST-1658        CBAC  Sprint4_AM_Europa       Medium  BBA02-14075   
1  SDPTST-3073        CBAC  Sprint4_AM_Europa          Low  BBA02-42408   
2  SDPTST-1360        CBAC  Sprint4_AM_Europa         High  BBA02-11401   
3  SDPTST-3071        CBAC  Sprint4_AM_Europa          Low  BBA02-36096   
4  SDPTST-8369        CBAC  Sprint4_AM_Europa         High    JMAP-5294   

       Defect2      Defect3      Defect4 DefectStatus1 DefectStatus2  \
0   BBA02-7530  SDPON-29022  SDPON-28992        Closed        Closed   
1  BBA02-36096  BBA02-29859  BBA02-24086        Closed        Closed   
2   BBA02-8089   BBA02-1335  SDPON-32283        Closed        Closed   
3  BBA02-30987  BBA02-29859  BBA02-25599        Closed        Closed   
4    JMAP-5197    JMAP-5295  BBA02-40188        Closed           WIP   

  DefectStatus3 DefectStatus4   Result    TestCaseId  
0        Closed        Closed     PASS  SDPTST-10269  
1      Assigned        Closed  Blocked  SDPTST-10269  
2        Closed        Closed     PASS  SDPTST-10269  
3      Assigned        Closed     FAIL  SDPTST-10269  
4        Closed        Closed     FAIL  SDPTST-10269

In [6]:
table_list.isnull().sum()

TestId           0
ProjectName      0
CycleName        0
TestPriority     0
Defect1          0
Defect2          0
Defect3          0
Defect4          0
DefectStatus1    0
DefectStatus2    0
DefectStatus3    0
DefectStatus4    0
Result           0
TestCaseId       0
dtype: int64

In [7]:
table_list=table_list.drop(['ProjectName'],axis=1)

In [8]:
table_list['Result'].value_counts()

Result
PASS          63303
Not Tested     9106
FAIL           6217
NA             1691
Blocked        1197
Name: count, dtype: int64

In [9]:
table_list.head()

TestId          CycleName TestPriority      Defect1      Defect2  \
0  SDPTST-1658  Sprint4_AM_Europa       Medium  BBA02-14075   BBA02-7530   
1  SDPTST-3073  Sprint4_AM_Europa          Low  BBA02-42408  BBA02-36096   
2  SDPTST-1360  Sprint4_AM_Europa         High  BBA02-11401   BBA02-8089   
3  SDPTST-3071  Sprint4_AM_Europa          Low  BBA02-36096  BBA02-30987   
4  SDPTST-8369  Sprint4_AM_Europa         High    JMAP-5294    JMAP-5197   

       Defect3      Defect4 DefectStatus1 DefectStatus2 DefectStatus3  \
0  SDPON-29022  SDPON-28992        Closed        Closed        Closed   
1  BBA02-29859  BBA02-24086        Closed        Closed      Assigned   
2   BBA02-1335  SDPON-32283        Closed        Closed        Closed   
3  BBA02-29859  BBA02-25599        Closed        Closed      Assigned   
4    JMAP-5295  BBA02-40188        Closed           WIP        Closed   

  DefectStatus4   Result    TestCaseId  
0        Closed     PASS  SDPTST-10269  
1        Closed  Blocked  SDPTST-10269  
2        Closed     PASS  SDPTST-10269  
3        Closed     FAIL  SDPTST-10269  
4        Closed     FAIL  SDPTST-10269

In [10]:
X = table_list.drop(['Result'] ,axis=1)  # All features
y = table_list['Result']              # Target


In [11]:
table_list.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81514 entries, 0 to 81513
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   TestId         81514 non-null  object
 1   CycleName      81514 non-null  object
 2   TestPriority   81514 non-null  object
 3   Defect1        81514 non-null  object
 4   Defect2        81514 non-null  object
 5   Defect3        81514 non-null  object
 6   Defect4        81514 non-null  object
 7   DefectStatus1  81514 non-null  object
 8   DefectStatus2  81514 non-null  object
 9   DefectStatus3  81514 non-null  object
 10  DefectStatus4  81514 non-null  object
 11  Result         81514 non-null  object
 12  TestCaseId     81514 non-null  object
dtypes: object(13)
memory usage: 8.1+ MB


In [12]:
print(len(X))
print(len(y))


81514
81514


In [13]:
table_list.tail()

TestId                CycleName TestPriority      Defect1  \
81509  BBA02-18987  PI2023.1-Sprint5-Manual    Very High  BBA02-21159   
81510  BBA02-18989  PI2023.1-Sprint5-Manual    Very High  BBA02-19868   
81511  BBA02-18996  PI2023.1-Sprint5-Manual    Very High         None   
81512  BBA02-18986  PI2023.1-Sprint5-Manual    Very High    JMAP-4273   
81513  BBA02-19000  PI2023.1-Sprint5-Manual    Very High         None   

         Defect2      Defect3 Defect4 DefectStatus1 DefectStatus2  \
81509  JMAP-4229  BBA02-21660    None        Closed        Closed   
81510       None         None    None        Closed          None   
81511       None         None    None          None          None   
81512       None         None    None        Closed          None   
81513       None         None    None          None          None   

      DefectStatus3 DefectStatus4 Result   TestCaseId  
81509        Closed          None   PASS  SDPTST-8207  
81510          None          None   PASS  SDPTST-8207  
81511          None          None   PASS  SDPTST-8207  
81512          None          None   PASS  SDPTST-8207  
81513          None          None   PASS  SDPTST-8207

In [14]:
X = X.loc[y.index]
y.shape



(81514,)

In [15]:
X['TestPriority'] = X['TestPriority'].str.strip().str.title()

# Then apply the mapping
priority_map = {
    'Low': 1,
    'Minor': 1,
    'Medium': 2,
    'High': 3,
    'Major': 3,
    'Very High': 3,
    'Critical': 3
}

X['TestPriority'] = X['TestPriority'].map(priority_map)

# Print to confirm
print(X)

            TestId                CycleName  TestPriority      Defect1  \
0      SDPTST-1658        Sprint4_AM_Europa             2  BBA02-14075   
1      SDPTST-3073        Sprint4_AM_Europa             1  BBA02-42408   
2      SDPTST-1360        Sprint4_AM_Europa             3  BBA02-11401   
3      SDPTST-3071        Sprint4_AM_Europa             1  BBA02-36096   
4      SDPTST-8369        Sprint4_AM_Europa             3    JMAP-5294   
...            ...                      ...           ...          ...   
81509  BBA02-18987  PI2023.1-Sprint5-Manual             3  BBA02-21159   
81510  BBA02-18989  PI2023.1-Sprint5-Manual             3  BBA02-19868   
81511  BBA02-18996  PI2023.1-Sprint5-Manual             3         None   
81512  BBA02-18986  PI2023.1-Sprint5-Manual             3    JMAP-4273   
81513  BBA02-19000  PI2023.1-Sprint5-Manual             3         None   

           Defect2      Defect3      Defect4 DefectStatus1 DefectStatus2  \
0       BBA02-7530  SDPON-29022  SD

In [16]:
print(y)

0           PASS
1        Blocked
2           PASS
3           FAIL
4           FAIL
          ...   
81509       PASS
81510       PASS
81511       PASS
81512       PASS
81513       PASS
Name: Result, Length: 81514, dtype: object


In [17]:
keep=['PASS','FAIL']
mask=y.isin(keep)
X_encoded=X.loc[mask]
table_list = table_list.loc[mask]
y=y.loc[mask]


In [18]:
y_encoded=y.map({'PASS':0,'FAIL':1}).astype(int)
print(y_encoded.value_counts())

Result
0    63303
1     6217
Name: count, dtype: int64


In [19]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=True, handle_unknown='ignore')

In [20]:
X_encoded_sparse = encoder.fit_transform(X_encoded[[
    'TestId','CycleName','TestPriority', 'Defect1', 'Defect2', 'Defect3', 'Defect4',
    'DefectStatus1', 'DefectStatus2', 'DefectStatus3', 'DefectStatus4',
]])

In [21]:
print("Length of X_encoded_sparse:", X_encoded_sparse.shape[0])
print("Length of table_list:", len(table_list))

Length of X_encoded_sparse: 69520
Length of table_list: 69520


In [22]:


table_list.head()
table_list.tail()



TestId                CycleName TestPriority      Defect1  \
81509  BBA02-18987  PI2023.1-Sprint5-Manual    Very High  BBA02-21159   
81510  BBA02-18989  PI2023.1-Sprint5-Manual    Very High  BBA02-19868   
81511  BBA02-18996  PI2023.1-Sprint5-Manual    Very High         None   
81512  BBA02-18986  PI2023.1-Sprint5-Manual    Very High    JMAP-4273   
81513  BBA02-19000  PI2023.1-Sprint5-Manual    Very High         None   

         Defect2      Defect3 Defect4 DefectStatus1 DefectStatus2  \
81509  JMAP-4229  BBA02-21660    None        Closed        Closed   
81510       None         None    None        Closed          None   
81511       None         None    None          None          None   
81512       None         None    None        Closed          None   
81513       None         None    None          None          None   

      DefectStatus3 DefectStatus4 Result   TestCaseId  
81509        Closed          None   PASS  SDPTST-8207  
81510          None          None   PASS  SDPTST-8207  
81511          None          None   PASS  SDPTST-8207  
81512          None          None   PASS  SDPTST-8207  
81513          None          None   PASS  SDPTST-8207

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded_sparse, y_encoded,test_size=0.20,random_state=42)

In [25]:
##Model training

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [26]:
models={
    "Logistic Regression": LogisticRegression(multi_class="ovr"),
    "Gradient Boost":GradientBoostingClassifier()


}
average_type = 'macro'
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train, y_train)
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    ## training test
    model_train_accuracy=accuracy_score(y_train, y_train_pred)
    model_train_confusion=confusion_matrix(y_train, y_train_pred)
   
    ##test performance
    model_test_accuracy=accuracy_score(y_test, y_test_pred)
    model_test_confusion=confusion_matrix(y_test, y_test_pred)
  
    print(list(models.keys())[i])
    print ("Model performance for training set data")
    print ("Accuracy: ", model_train_accuracy)
    print ("Confusion Matrix:\n", model_train_confusion)

    print("---------------------------------------")
    print ("Model performance for test set data")
    print ("Accuracy: ", model_test_accuracy)
    print ("Confusion Matrix:\n", model_test_confusion)
  
    print("---------------------------------------")
    probs=model.predict_proba(X_encoded_sparse)
    print(probs)
    print("="*32)
    probabilities = probs[:,1]

for model_name, model in models.items():
    model.fit(X_train, y_train)

    probs = model.predict_proba(X_encoded_sparse)
    print(probs)
    probabilities = probs[:, 1]

    def assign_rank(p):
        if p >= 0.8:
            return 1
        elif p >= 0.6:
            return 2
        elif p >= 0.4:
            return 3
        elif p >= 0.2:
            return 4
        else:
            return 5

    ranks = [assign_rank(p) for p in probabilities]
    
    # Create a DataFrame with the ranks
    results = pd.DataFrame({
        "Predicted_Prob": probabilities,
        "Assigned_Rank": ranks
    })
    table_list[f"Ranks by {model_name}"] = np.nan
    table_list.loc[mask, f"Ranks by {model_name}"] = ranks

c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression
Model performance for training set data
Accuracy:  0.9357558975834293
Confusion Matrix:
 [[50134   523]
 [ 3050  1909]]
---------------------------------------
Model performance for test set data
Accuracy:  0.9148446490218642
Confusion Matrix:
 [[12389   257]
 [  927   331]]
---------------------------------------
[[0.9976213  0.0023787 ]
 [0.96800771 0.03199229]
 [0.94304928 0.05695072]
 ...
 [0.9802631  0.0197369 ]
 [0.83930324 0.16069676]
 [0.98032319 0.01967681]]
Gradient Boost
Model performance for training set data
Accuracy:  0.914449079401611
Confusion Matrix:
 [[50539   118]
 [ 4640   319]]
---------------------------------------
Model performance for test set data
Accuracy:  0.9116800920598389
Confusion Matrix:
 [[12597    49]
 [ 1179    79]]
---------------------------------------
[[0.91219793 0.08780207]
 [0.91219793 0.08780207]
 [0.86833097 0.13166903]
 ...
 [0.96866903 0.03133097]
 [0.90674635 0.09325365]
 [0.96866903 0.03133097]]


c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[0.9976213  0.0023787 ]
 [0.96800771 0.03199229]
 [0.94304928 0.05695072]
 ...
 [0.9802631  0.0197369 ]
 [0.83930324 0.16069676]
 [0.98032319 0.01967681]]
[[0.91219793 0.08780207]
 [0.91219793 0.08780207]
 [0.86833097 0.13166903]
 ...
 [0.96866903 0.03133097]
 [0.90674635 0.09325365]
 [0.96866903 0.03133097]]


In [27]:
print(probs)

[[0.91219793 0.08780207]
 [0.91219793 0.08780207]
 [0.86833097 0.13166903]
 ...
 [0.96866903 0.03133097]
 [0.90674635 0.09325365]
 [0.96866903 0.03133097]]


In [28]:
table_list

TestId                CycleName TestPriority      Defect1  \
0      SDPTST-1658        Sprint4_AM_Europa       Medium  BBA02-14075   
2      SDPTST-1360        Sprint4_AM_Europa         High  BBA02-11401   
3      SDPTST-3071        Sprint4_AM_Europa          Low  BBA02-36096   
4      SDPTST-8369        Sprint4_AM_Europa         High    JMAP-5294   
5        SDPTST-91        Sprint4_AM_Europa         High  BBA02-14075   
...            ...                      ...          ...          ...   
81509  BBA02-18987  PI2023.1-Sprint5-Manual    Very High  BBA02-21159   
81510  BBA02-18989  PI2023.1-Sprint5-Manual    Very High  BBA02-19868   
81511  BBA02-18996  PI2023.1-Sprint5-Manual    Very High         None   
81512  BBA02-18986  PI2023.1-Sprint5-Manual    Very High    JMAP-4273   
81513  BBA02-19000  PI2023.1-Sprint5-Manual    Very High         None   

           Defect2      Defect3      Defect4 DefectStatus1 DefectStatus2  \
0       BBA02-7530  SDPON-29022  SDPON-28992        Closed        Closed   
2       BBA02-8089   BBA02-1335  SDPON-32283        Closed        Closed   
3      BBA02-30987  BBA02-29859  BBA02-25599        Closed        Closed   
4        JMAP-5197    JMAP-5295  BBA02-40188        Closed           WIP   
5       BBA02-7530  SDPON-13623  SDPON-12779        Closed        Closed   
...            ...          ...          ...           ...           ...   
81509    JMAP-4229  BBA02-21660         None        Closed        Closed   
81510         None         None         None        Closed          None   
81511         None         None         None          None          None   
81512         None         None         None        Closed          None   
81513         None         None         None          None          None   

      DefectStatus3 DefectStatus4 Result    TestCaseId  \
0            Closed        Closed   PASS  SDPTST-10269   
2            Closed        Closed   PASS  SDPTST-10269   
3          Assigned        Closed   FAIL  SDPTST-10269   
4            Closed        Closed   FAIL  SDPTST-10269   
5            Closed        Closed   PASS  SDPTST-10269   
...             ...           ...    ...           ...   
81509        Closed          None   PASS   SDPTST-8207   
81510          None          None   PASS   SDPTST-8207   
81511          None          None   PASS   SDPTST-8207   
81512          None          None   PASS   SDPTST-8207   
81513          None          None   PASS   SDPTST-8207   

       Ranks by Logistic Regression  Ranks by Gradient Boost  
0                               5.0                      5.0  
2                               5.0                      5.0  
3                               5.0                      5.0  
4                               5.0                      5.0  
5                               5.0                      5.0  
...                             ...                      ...  
81509                           4.0                      5.0  
81510                           5.0                      5.0  
81511                           5.0                      5.0  
81512                           5.0                      5.0  
81513                           5.0                      5.0  

[69520 rows x 15 columns]

In [29]:
table_list.tail()

TestId                CycleName TestPriority      Defect1  \
81509  BBA02-18987  PI2023.1-Sprint5-Manual    Very High  BBA02-21159   
81510  BBA02-18989  PI2023.1-Sprint5-Manual    Very High  BBA02-19868   
81511  BBA02-18996  PI2023.1-Sprint5-Manual    Very High         None   
81512  BBA02-18986  PI2023.1-Sprint5-Manual    Very High    JMAP-4273   
81513  BBA02-19000  PI2023.1-Sprint5-Manual    Very High         None   

         Defect2      Defect3 Defect4 DefectStatus1 DefectStatus2  \
81509  JMAP-4229  BBA02-21660    None        Closed        Closed   
81510       None         None    None        Closed          None   
81511       None         None    None          None          None   
81512       None         None    None        Closed          None   
81513       None         None    None          None          None   

      DefectStatus3 DefectStatus4 Result   TestCaseId  \
81509        Closed          None   PASS  SDPTST-8207   
81510          None          None   PASS  SDPTST-8207   
81511          None          None   PASS  SDPTST-8207   
81512          None          None   PASS  SDPTST-8207   
81513          None          None   PASS  SDPTST-8207   

       Ranks by Logistic Regression  Ranks by Gradient Boost  
81509                           4.0                      5.0  
81510                           5.0                      5.0  
81511                           5.0                      5.0  
81512                           5.0                      5.0  
81513                           5.0                      5.0

In [30]:
table_list['Ranks by Logistic Regression'].value_counts()

Ranks by Logistic Regression
5.0    59908
4.0     5197
3.0     2347
2.0     1354
1.0      714
Name: count, dtype: int64

In [31]:
table_list['Ranks by Gradient Boost'].value_counts()

Ranks by Gradient Boost
5.0    63800
4.0     4469
3.0     1023
2.0      220
1.0        8
Name: count, dtype: int64

In [32]:
new_df = table_list[["TestId", "Ranks by Logistic Regression", "Ranks by Gradient Boost"]]

In [33]:
new_df

TestId  Ranks by Logistic Regression  Ranks by Gradient Boost
0      SDPTST-1658                           5.0                      5.0
2      SDPTST-1360                           5.0                      5.0
3      SDPTST-3071                           5.0                      5.0
4      SDPTST-8369                           5.0                      5.0
5        SDPTST-91                           5.0                      5.0
...            ...                           ...                      ...
81509  BBA02-18987                           4.0                      5.0
81510  BBA02-18989                           5.0                      5.0
81511  BBA02-18996                           5.0                      5.0
81512  BBA02-18986                           5.0                      5.0
81513  BBA02-19000                           5.0                      5.0

[69520 rows x 3 columns]

HYPERPARAMETER TUNING

In [34]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [35]:
params={'penalty':penalty,'C':c_values,'solver':solver}

In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [37]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy',n_iter=10,n_jobs=-1,random_state=42)

In [38]:
randomcv.fit(X_train,y_train)

c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logist

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   random_state=42, scoring='accuracy')

In [39]:
randomcv.best_score_

np.float64(0.9147547367035719)

In [40]:
randomcv.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [41]:
model=LogisticRegression(solver='newton-cg',penalty='l2',C=100)

In [42]:
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

In [43]:
score=accuracy_score(y_pred,y_test)
print(score)
print(confusion_matrix(y_test,y_pred))

0.9102416570771001
[[12269   377]
 [  871   387]]
