In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('dummy.sqlite3')


In [3]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)


         name
0  regression


In [4]:
table_list = pd.read_sql_query("SELECT * FROM regression;", conn)
print(table_list)



            TestId ProjectName                CycleName TestPriority  \
0      SDPTST-1658        CBAC        Sprint4_AM_Europa       Medium   
1      SDPTST-3073        CBAC        Sprint4_AM_Europa          Low   
2      SDPTST-1360        CBAC        Sprint4_AM_Europa         High   
3      SDPTST-3071        CBAC        Sprint4_AM_Europa          Low   
4      SDPTST-8369        CBAC        Sprint4_AM_Europa         High   
...            ...         ...                      ...          ...   
81509  BBA02-18987        CBAC  PI2023.1-Sprint5-Manual    Very High   
81510  BBA02-18989        CBAC  PI2023.1-Sprint5-Manual    Very High   
81511  BBA02-18996        CBAC  PI2023.1-Sprint5-Manual    Very High   
81512  BBA02-18986        CBAC  PI2023.1-Sprint5-Manual    Very High   
81513  BBA02-19000        CBAC  PI2023.1-Sprint5-Manual    Very High   

           Defect1      Defect2      Defect3      Defect4 DefectStatus1  \
0      BBA02-14075   BBA02-7530  SDPON-29022  SDPON-28992   

In [5]:
table_list.head()

TestId ProjectName          CycleName TestPriority      Defect1  \
0  SDPTST-1658        CBAC  Sprint4_AM_Europa       Medium  BBA02-14075   
1  SDPTST-3073        CBAC  Sprint4_AM_Europa          Low  BBA02-42408   
2  SDPTST-1360        CBAC  Sprint4_AM_Europa         High  BBA02-11401   
3  SDPTST-3071        CBAC  Sprint4_AM_Europa          Low  BBA02-36096   
4  SDPTST-8369        CBAC  Sprint4_AM_Europa         High    JMAP-5294   

       Defect2      Defect3      Defect4 DefectStatus1 DefectStatus2  \
0   BBA02-7530  SDPON-29022  SDPON-28992        Closed        Closed   
1  BBA02-36096  BBA02-29859  BBA02-24086        Closed        Closed   
2   BBA02-8089   BBA02-1335  SDPON-32283        Closed        Closed   
3  BBA02-30987  BBA02-29859  BBA02-25599        Closed        Closed   
4    JMAP-5197    JMAP-5295  BBA02-40188        Closed           WIP   

  DefectStatus3 DefectStatus4   Result    TestCaseId  
0        Closed        Closed     PASS  SDPTST-10269  
1      Assigned        Closed  Blocked  SDPTST-10269  
2        Closed        Closed     PASS  SDPTST-10269  
3      Assigned        Closed     FAIL  SDPTST-10269  
4        Closed        Closed     FAIL  SDPTST-10269

In [6]:
table_list.isnull().sum()

TestId           0
ProjectName      0
CycleName        0
TestPriority     0
Defect1          0
Defect2          0
Defect3          0
Defect4          0
DefectStatus1    0
DefectStatus2    0
DefectStatus3    0
DefectStatus4    0
Result           0
TestCaseId       0
dtype: int64

In [7]:
table_list=table_list.drop(['ProjectName'],axis=1)

In [8]:
table_list=table_list.drop(['TestId'],axis=1)

In [9]:
table_list['Result'].value_counts()

Result
PASS          63303
Not Tested     9106
FAIL           6217
NA             1691
Blocked        1197
Name: count, dtype: int64

In [10]:
table_list.head()

CycleName TestPriority      Defect1      Defect2      Defect3  \
0  Sprint4_AM_Europa       Medium  BBA02-14075   BBA02-7530  SDPON-29022   
1  Sprint4_AM_Europa          Low  BBA02-42408  BBA02-36096  BBA02-29859   
2  Sprint4_AM_Europa         High  BBA02-11401   BBA02-8089   BBA02-1335   
3  Sprint4_AM_Europa          Low  BBA02-36096  BBA02-30987  BBA02-29859   
4  Sprint4_AM_Europa         High    JMAP-5294    JMAP-5197    JMAP-5295   

       Defect4 DefectStatus1 DefectStatus2 DefectStatus3 DefectStatus4  \
0  SDPON-28992        Closed        Closed        Closed        Closed   
1  BBA02-24086        Closed        Closed      Assigned        Closed   
2  SDPON-32283        Closed        Closed        Closed        Closed   
3  BBA02-25599        Closed        Closed      Assigned        Closed   
4  BBA02-40188        Closed           WIP        Closed        Closed   

    Result    TestCaseId  
0     PASS  SDPTST-10269  
1  Blocked  SDPTST-10269  
2     PASS  SDPTST-10269  
3     FAIL  SDPTST-10269  
4     FAIL  SDPTST-10269

In [12]:
X = table_list.drop(['Result','CycleName'] ,axis=1)  # All features
y = table_list['Result']              # Target


In [13]:
table_list.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81514 entries, 0 to 81513
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   CycleName      81514 non-null  object
 1   TestPriority   81514 non-null  object
 2   Defect1        81514 non-null  object
 3   Defect2        81514 non-null  object
 4   Defect3        81514 non-null  object
 5   Defect4        81514 non-null  object
 6   DefectStatus1  81514 non-null  object
 7   DefectStatus2  81514 non-null  object
 8   DefectStatus3  81514 non-null  object
 9   DefectStatus4  81514 non-null  object
 10  Result         81514 non-null  object
 11  TestCaseId     81514 non-null  object
dtypes: object(12)
memory usage: 7.5+ MB


In [14]:
print(len(X))
print(len(y))


81514
81514


In [15]:
table_list.tail()

CycleName TestPriority      Defect1    Defect2  \
81509  PI2023.1-Sprint5-Manual    Very High  BBA02-21159  JMAP-4229   
81510  PI2023.1-Sprint5-Manual    Very High  BBA02-19868       None   
81511  PI2023.1-Sprint5-Manual    Very High         None       None   
81512  PI2023.1-Sprint5-Manual    Very High    JMAP-4273       None   
81513  PI2023.1-Sprint5-Manual    Very High         None       None   

           Defect3 Defect4 DefectStatus1 DefectStatus2 DefectStatus3  \
81509  BBA02-21660    None        Closed        Closed        Closed   
81510         None    None        Closed          None          None   
81511         None    None          None          None          None   
81512         None    None        Closed          None          None   
81513         None    None          None          None          None   

      DefectStatus4 Result   TestCaseId  
81509          None   PASS  SDPTST-8207  
81510          None   PASS  SDPTST-8207  
81511          None   PASS  SDPTST-8207  
81512          None   PASS  SDPTST-8207  
81513          None   PASS  SDPTST-8207

In [16]:
X = X.loc[y.index]
y.shape



(81514,)

In [17]:
X['TestPriority'] = X['TestPriority'].str.strip().str.title()

# Then apply the mapping
priority_map = {
    'Low': 1,
    'Minor': 1,
    'Medium': 2,
    'High': 3,
    'Major': 3,
    'Very High': 3,
    'Critical': 3
}

X['TestPriority'] = X['TestPriority'].map(priority_map)

# Print to confirm
print(X)

       TestPriority      Defect1      Defect2      Defect3      Defect4  \
0                 2  BBA02-14075   BBA02-7530  SDPON-29022  SDPON-28992   
1                 1  BBA02-42408  BBA02-36096  BBA02-29859  BBA02-24086   
2                 3  BBA02-11401   BBA02-8089   BBA02-1335  SDPON-32283   
3                 1  BBA02-36096  BBA02-30987  BBA02-29859  BBA02-25599   
4                 3    JMAP-5294    JMAP-5197    JMAP-5295  BBA02-40188   
...             ...          ...          ...          ...          ...   
81509             3  BBA02-21159    JMAP-4229  BBA02-21660         None   
81510             3  BBA02-19868         None         None         None   
81511             3         None         None         None         None   
81512             3    JMAP-4273         None         None         None   
81513             3         None         None         None         None   

      DefectStatus1 DefectStatus2 DefectStatus3 DefectStatus4    TestCaseId  
0            Closed  

In [18]:
print(y)

0           PASS
1        Blocked
2           PASS
3           FAIL
4           FAIL
          ...   
81509       PASS
81510       PASS
81511       PASS
81512       PASS
81513       PASS
Name: Result, Length: 81514, dtype: object


In [19]:
keep=['PASS','FAIL']
mask=y.isin(keep)
X_encoded=X.loc[mask]
y=y.loc[mask]


In [20]:
y_encoded=y.map({'PASS':0,'FAIL':1}).astype(int)
print(y_encoded.value_counts())

Result
0    63303
1     6217
Name: count, dtype: int64


In [22]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=True, handle_unknown='ignore')

In [25]:
X_encoded_sparse = encoder.fit_transform(X_encoded[[
    'TestPriority', 'Defect1', 'Defect2', 'Defect3', 'Defect4',
    'DefectStatus1', 'DefectStatus2', 'DefectStatus3', 'DefectStatus4',
]])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded_sparse, y_encoded,test_size=0.20,random_state=42)

In [27]:
##Model training

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
models={
    "Logistic Regression": LogisticRegression(multi_class="ovr"),
    "Gradient Boost":GradientBoostingClassifier()


}
average_type = 'macro'
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train, y_train)
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    ## training test
    model_train_accuracy=accuracy_score(y_train, y_train_pred)
    model_train_confusion=confusion_matrix(y_train, y_train_pred)
   
    ##test performance
    model_test_accuracy=accuracy_score(y_test, y_test_pred)
    model_test_confusion=confusion_matrix(y_test, y_test_pred)
  
    print(list(models.keys())[i])
    print ("Model performance for training set data")
    print ("Accuracy: ", model_train_accuracy)
    print ("Confusion Matrix:\n", model_train_confusion)

    print("---------------------------------------")
    print ("Model performance for test set data")
    print ("Accuracy: ", model_test_accuracy)
    print ("Confusion Matrix:\n", model_test_confusion)
  
    print("---------------------------------------")
    probs=model.predict_proba(X_encoded_sparse)
    print(probs)
    print("="*32)
    probabilities = probs[:,1]

for model_name, model in models.items():
    model.fit(X_train, y_train)

    probs = model.predict_proba(X_encoded_sparse)
    print(probs)
    probabilities = probs[:, 1]

    def assign_rank(p):
        if p >= 0.8:
            return 1
        elif p >= 0.6:
            return 2
        elif p >= 0.4:
            return 3
        elif p >= 0.2:
            return 4
        else:
            return 5

    ranks = [assign_rank(p) for p in probabilities]
    
    # Create a DataFrame with the ranks
    results = pd.DataFrame({
        "Predicted_Prob": probabilities,
        "Assigned_Rank": ranks
    })

    table_list[f"Ranks by {model_name}"] = results["Assigned_Rank"]


c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without featur

Logistic Regression
Model performance for training set data
Accuracy:  0.9291211162255466
Confusion Matrix:
 [[50273   384]
 [ 3558  1401]]
---------------------------------------
Model performance for test set data
Accuracy:  0.9138377445339471
Confusion Matrix:
 [[12456   190]
 [ 1008   250]]
---------------------------------------


ValueError: could not convert string to float: 'BBA02-14075'

In [26]:
print(probs)

[[0.91681058 0.08318942]
 [0.89973909 0.10026091]
 [0.94595831 0.05404169]
 ...
 [0.89973909 0.10026091]
 [0.89973909 0.10026091]
 [0.89973909 0.10026091]]


In [23]:
table_list

TestId                CycleName TestPriority      Defect1  \
0      SDPTST-1658        Sprint4_AM_Europa       Medium  BBA02-14075   
1      SDPTST-3073        Sprint4_AM_Europa          Low  BBA02-42408   
2      SDPTST-1360        Sprint4_AM_Europa         High  BBA02-11401   
3      SDPTST-3071        Sprint4_AM_Europa          Low  BBA02-36096   
4      SDPTST-8369        Sprint4_AM_Europa         High    JMAP-5294   
...            ...                      ...          ...          ...   
81509  BBA02-18987  PI2023.1-Sprint5-Manual    Very High  BBA02-21159   
81510  BBA02-18989  PI2023.1-Sprint5-Manual    Very High  BBA02-19868   
81511  BBA02-18996  PI2023.1-Sprint5-Manual    Very High         None   
81512  BBA02-18986  PI2023.1-Sprint5-Manual    Very High    JMAP-4273   
81513  BBA02-19000  PI2023.1-Sprint5-Manual    Very High         None   

           Defect2      Defect3      Defect4 DefectStatus1 DefectStatus2  \
0       BBA02-7530  SDPON-29022  SDPON-28992        Closed        Closed   
1      BBA02-36096  BBA02-29859  BBA02-24086        Closed        Closed   
2       BBA02-8089   BBA02-1335  SDPON-32283        Closed        Closed   
3      BBA02-30987  BBA02-29859  BBA02-25599        Closed        Closed   
4        JMAP-5197    JMAP-5295  BBA02-40188        Closed           WIP   
...            ...          ...          ...           ...           ...   
81509    JMAP-4229  BBA02-21660         None        Closed        Closed   
81510         None         None         None        Closed          None   
81511         None         None         None          None          None   
81512         None         None         None        Closed          None   
81513         None         None         None          None          None   

      DefectStatus3 DefectStatus4   Result    TestCaseId  \
0            Closed        Closed     PASS  SDPTST-10269   
1          Assigned        Closed  Blocked  SDPTST-10269   
2            Closed        Closed     PASS  SDPTST-10269   
3          Assigned        Closed     FAIL  SDPTST-10269   
4            Closed        Closed     FAIL  SDPTST-10269   
...             ...           ...      ...           ...   
81509        Closed          None     PASS   SDPTST-8207   
81510          None          None     PASS   SDPTST-8207   
81511          None          None     PASS   SDPTST-8207   
81512          None          None     PASS   SDPTST-8207   
81513          None          None     PASS   SDPTST-8207   

       Ranks by Logistic Regression  Ranks by Gradient Boost  
0                               5.0                      5.0  
1                               5.0                      5.0  
2                               5.0                      5.0  
3                               5.0                      5.0  
4                               5.0                      5.0  
...                             ...                      ...  
81509                           NaN                      NaN  
81510                           NaN                      NaN  
81511                           NaN                      NaN  
81512                           NaN                      NaN  
81513                           NaN                      NaN  

[81514 rows x 15 columns]

HYPERPARAMETER TUNING

In [ ]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [ ]:
params={'penalty':penalty,'C':c_values,'solver':solver}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy',n_iter=10,n_jobs=-1,random_state=42)

In [ ]:
randomcv.fit(X_train,y_train)

c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logist

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   random_state=42, scoring='accuracy')

In [ ]:
randomcv.best_score_

np.float64(0.8806182828451907)

In [ ]:
randomcv.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [ ]:
model=LogisticRegression(solver='lbfgs',penalty='l2',C=0.1)

In [ ]:
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

c:\Users\Lenovo\Desktop\Dummy\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8757283935471999
              precision    recall  f1-score   support

           0       0.54      0.05      0.09       272
           1       0.50      0.19      0.28      1260
           2       0.33      0.07      0.12       347
           3       0.98      0.88      0.93      1803
           4       0.88      0.98      0.93     12621

    accuracy                           0.88     16303
   macro avg       0.65      0.44      0.47     16303
weighted avg       0.84      0.88      0.85     16303

[[   13    29     3     1   226]
 [    2   241     8     5  1004]
 [    2    26    26    21   272]
 [    0    20     0  1592   191]
 [    7   165    42     2 12405]]
